project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!/assets/"

execute: 
  freeze: auto

website:
  title: "SOCIOL 213B: Applied Event History Analysis"
  description: "A course on survival models and causal inference with treatments over time."
  navbar:
    pinned: true
    right:
      - href: problem_sets.qmd
        text: Problem Sets
      - href: datasets.qmd
        text: Data
      - href: assets/syllabus.pdf
        text: Syllabus
      - about_me.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - survival_concepts.qmd
      - kaplanmeier.qmd
      - bernoulli.qmd
      - exponential.qmd
      - weibull.qmd
      - lognormal.qmd
      - piecewise_exponential.qmd
      - proportional_hazards.qmd
      - cox.qmd
      - unmeasured_heterogeneity.qmd
      - competing_risks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
